version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: mariadb
    restart: always
    hostname: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TestSpeedFlask

  web:
    image:  flastestspeed
    links:
      - db
    restart: always
    ports:
      - 5001:5000